from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def render_pdf(session_payload: dict, output_path: str) -> str:
    patient = session_payload.get("patient", {})
    gaps = session_payload.get("gaps", [])
    created_at = session_payload.get("created_at", "")

    doc = SimpleDocTemplate(output_path, pagesize=letter,
                            leftMargin=0.75 * inch, rightMargin=0.75 * inch,
                            topMargin=0.75 * inch, bottomMargin=0.75 * inch)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("title", parent=styles["Heading1"], fontSize=18, spaceAfter=4)
    meta_style = ParagraphStyle("meta", parent=styles["Normal"], fontSize=10, textColor=colors.HexColor("#444444"), spaceAfter=16)
    cell_style = ParagraphStyle("cell", parent=styles["Normal"], fontSize=9, leading=12)

    story = [
        Paragraph("TransitionGuard Gap Report", title_style),
        Paragraph(
            f"Patient: <b>{patient.get('name', 'Unknown')}</b> &nbsp;|&nbsp; "
            f"DOB: {patient.get('dob', 'Unknown')} &nbsp;|&nbsp; "
            f"Generated: {str(created_at)[:19]}",
            meta_style,
        ),
    ]

    if not gaps:
        story.append(Paragraph("No care gaps identified.", styles["Normal"]))
    else:
        headers = ["Severity", "Category", "Title", "Description", "Suggested Action"]
        header_row = [Paragraph(f"<b>{h}</b>", cell_style) for h in headers]
        rows = [header_row]
        for g in gaps:
            rows.append([
                Paragraph(g.get("severity", ""), cell_style),
                Paragraph(g.get("category", ""), cell_style),
                Paragraph(g.get("title", ""), cell_style),
                Paragraph(g.get("description", ""), cell_style),
                Paragraph(g.get("suggested_action", ""), cell_style),
            ])

        col_widths = [0.8 * inch, 0.9 * inch, 1.4 * inch, 2.4 * inch, 2.0 * inch]
        table = Table(rows, colWidths=col_widths, repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0b5f2b")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f4f6ef")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(table)

    story.append(Spacer(1, 0.3 * inch))
    story.append(Paragraph("Generated by TransitionGuard · Clinical Handoff Integrity System",
                            ParagraphStyle("footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey)))

    doc.build(story)
    return output_path
